# Generated by Django 5.1 on 2024-11-08 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Creator'), ('viewers', 'viewers')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='creatorProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='viewersProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewersProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='recruiterProfileModel',
        ),
        migrations.DeleteModel(
            name='seekerProfileModel',
        ),
    ]
