# Generated by Django 5.1 on 2024-11-08 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_seekerprofilemodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100, null=True)),
                ('Difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=100, null=True)),
                ('Tag', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('nonVegetarian', 'NonVegetarian')], max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('ingredients', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
                ('prep_time', models.PositiveIntegerField(null=True)),
                ('cooking_time', models.PositiveIntegerField(null=True)),
                ('total_time', models.PositiveIntegerField(null=True)),
                ('nutrition', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Media/Recipe_Image')),
                ('calories', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
