# Generated by Django 5.1 on 2024-11-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_creatorprofilemodel_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='Followers',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
